TRAIT_CARD_MIN_FOOD_TOKENS = -3
TRAIT_CARD_MAX_FOOD_TOKENS = 3
CARNIVORE_MIN_FOOD_TOKENS = -8
CARNIVORE_MAX_FOOD_TOKENS = 8
FAT_TISSUE_STARTING_FOOD = 0
TRAIT_CARD_DEFAULT_FOOD_TOKENS = 0
TRAIT_CARD_DEFAULT_DESC = ""
HARD_SHELL_OFFSET = 4
SPECIES_START_FOOD = 0
SPECIES_START_POP = 1
SPECIES_EXTINCTION_POP = 0
SPECIES_MAX_POP = 7
SPECIES_START_BODY_SIZE = 0
SPECIES_MIN_BODY_SIZE = 0
SPECIES_MAX_BODY_SIZE = 7
SPECIES_MAX_TRAITS_PER_SPECIES = 3
MIN_BOARD_FOOD_TOKENS = 0
STARTING_BOARD_FOOD_TOKENS = 0
GEN_TRAIT_CARD_STORED_FOOD = 0
DEFAULT_WATER_HOLE = 0
DEFAULT_ID = 1
PLAYER_STARTING_FOOD_TOKENS = 0
NO_FAT_FOOD = 0
MIN_NUM_PLAYERS = 3
MAX_NUM_PLAYERS = 8
DEFAULT_FOOD_BAG = 0
NUM_TOKENS_FOR_NORMAL_FEED = 1
NUM_TOKENS_FOR_FORAGING_FEED = 2
DEFAULT_TRAIT_CARD_FOOD_WANT = 0
NO_DAMAGE = 0
DEFAULT_DAMAGE = 1
CURRENT_PLAYER_INDEX = 0
AUTOMATE_COUNT = 1
DEFAULT_START_INDEX = 0
EXTINCT_DRAW_CARD = 2
NO_FOOD_TOKENS = 0
DEFAULT_FOOD_TOKENS_GRABBED = 1
AFTER_CURRENT_PLAYER_INDEX_OFFSET = 1
GAIN_FOR_ATTRIBUTE = 1
EMPTY_LIST_LEN = 0
FERTILE_POP_INCREASE = 1
MINIMUM_HAND_SIZE = 3
ONE_CARNIVORE_FORGO_ATTACK = 1
NO_SPECIES = 0
NO_PLAYERS_IN_GAME = 0
NUM_PLAYERS_ARGV_LEN = 2
HASNT_FORGON = False
HAS_FORGON = True
IS_INSTANCE_STR = "is_instance"

CARNIVORE_STR = "carnivore"
AMBUSH_STR = "ambush"
BURROWING_STR = "burrowing"
CLIMBING_STR = "climbing"
COOPERATION_STR = "cooperation"
FAT_TISSUE_STR = "fat-tissue"
FERTILE_STR = "fertile"
FORAGING_STR = "foraging"
HARD_SHELL_STR = "hard-shell"
HERDING_STR = "herding"
HORNS_STR = "horns"
LONG_NECK_STR = "long-neck"
PACK_HUNTING_STR = "pack-hunting"
SCAVENGER_STR = "scavenger"
SYMBIOSIS_STR = "symbiosis"
WARNING_CALL_STR = "warning-call"

PACKET_SIZE = 4096
NO_ID = 0
START_PLAYER_ID = 1
INVALID_SOCKET = -1
SERVER_HOST_ADDRESS = "localhost"
SERVER_PORT_ADDRESS = 45678

CLIENT_HOST_ADDRESS = "localhost"
CLIENT_PORT_ADDRESS = 45678

ID_STR = "id"
SPECIES_STR = "species"
BAG_STR = "bag"
FOOD_STR = "food"
BODY_STR = "body"
POP_STR = "population"
TRAITS_STR = "traits"
FAT_FOOD_STR = "fat-food"
CARDS_STR = "cards"

PJ_FIELD_LEN = 2
PJ_OPT = False

PJ_SPECIES_LEN = 4
PJ_SPECIES_PLUS_LEN = PJ_SPECIES_LEN + 1

PJ_FEEDING_LEN = 3
PJ_SIT_LEN = 4
PJ_CONFIG_LEN = 3
PJ_SPECIES_CARD_LEN = 2

PJ_PLAYER_LEN = 3
PJ_PLAYER_PLUS_LEN = PJ_PLAYER_LEN + 1

PJ_STEP4_CONFIG_LEN = 2

PJ_GP_AND_GB_LEN = 3
NEW_PJ_GP_AND_GB_LEN = 2
MIN_PJ_BT_LEN = 1
MAX_PJ_BT_LEN = 4
PJ_RT_LEN = 3
PJ_ACTION4_LEN = 5

PJ_CHOICE_LEN = 3

PJ_PLAYER_STATE_LEN = 4
PJ_GAME_STATE_LEN = 5

OKAY = "ok"
SERVER_CHOOSE_ACTION_LEN = 2
PLAYER_CONFIG_LEN = 4

PYJSON_NULL = None
HELLO_WORLD_STR = "hello world"

START_MESSAGE = "\nEvolution Begins ..."

TUPLE_STR = "Tuple"
LIST_STR = "List"
NAME_STR = "__name__"
NO_CARDS_WANTED = 0


START_CONNECTION_TIMEOUT = 5
SERVER_MESSAGE_TIMEOUT = 5
CLIENT_MESSAGE_TIMEOUT = 30
NEW_SPECIES_AT_START_OF_TURN = 1


CLIENT_THREAD_TIMEOUT = 2
MAX_NUM_CLIENT_THREADS = 20

CLASS_STR = "Class"