from evolution.all_interfaces import *

POSN_DEFAULT_X_OFFSET = 0
POSN_DEFAULT_Y_OFFSET = 0


NAME_POSN_X_OFFSET = 50
NAME_POSN_Y_OFFSET = 50

SPECIES_IMAGE_WIDTH = 250
TRAIT_CARD_IMAGE_WIDTH = 125

SPECIES_IMAGE_ATTRIBUTE_HEIGHT = 30
SPECIES_ATTRIBUTE_TEXT_WIDTH = 105

TRAIT_CARD_IMAGE_HEIGHT = 100
TEXT_HEIGHT = 30

NUM_SPECIES_IMAGE_SLOTS = 4
NUM_TRAIT_CARD_IMAGE_SLOTS = int(NUM_SPECIES_IMAGE_SLOTS * (SPECIES_IMAGE_WIDTH / TRAIT_CARD_IMAGE_WIDTH))
PLAYER_IMAGE_WIDTH = SPECIES_IMAGE_WIDTH * NUM_SPECIES_IMAGE_SLOTS


MAX_NUMBER_DISPLAY_TOKENS = max(SPECIES_MAX_BODY_SIZE, SPECIES_MAX_POP)


DEFAULT_OUTLINE_WIDTH = 2

POP_STR = "Population"
POP_COMP_INDEX = 0
BODY_STR = "Body Size"
BODY_COMP_INDEX = 1
TRAITS_COMP_INDEX = 2

NUM_DRAW_SPECIES_COMP_WITH_TRAITS = 3
NUM_DRAW_SPECIES_COMP_WITHOUT_TRAITS = NUM_DRAW_SPECIES_COMP_WITH_TRAITS - 1

DEFAULT_HEIGHT_THICKNESS = 0

FILL_STR = "fill"
BORDER_WIDTH_STR = "width"
TEXT_STR = "text"

DEFAULT_HAS_BORDER = False
